In [1]:
import numpy as np
import pandas as pd
import acquire
import prepare

In [15]:
df = prepare.prep_telco(acquire.get_telco_data())

opening data from file

In [17]:
df.columns

Index(['customer_id', 'gender', 'senior_citizen', 'partner', 'dependents',
       'tenure', 'phone_service', 'multiple_lines', 'online_security',
       'online_backup', 'device_protection', 'tech_support', 'streaming_tv',
       'streaming_movies', 'paperless_billing', 'monthly_charges',
       'total_charges', 'churn', 'contract_type', 'internet_service_type',
       'payment_type', 'gender_male', 'multiple_lines_no_phone_service',
       'multiple_lines_yes', 'online_security_no_internet_service',
       'online_security_yes', 'online_backup_no_internet_service',
       'online_backup_yes', 'device_protection_no_internet_service',
       'device_protection_yes', 'tech_support_no_internet_service',
       'tech_support_yes', 'streaming_tv_no_internet_service',
       'streaming_tv_yes', 'streaming_movies_no_internet_service',
       'streaming_movies_yes', 'contract_type_one_year',
       'contract_type_two_year', 'internet_service_type_fiber_optic',
       'internet_service_type_none', 'payment_type_credit_card_automatic',
       'payment_type_electronic_check', 'payment_type_mailed_check'],
      dtype='object')

In [18]:
pd.concat([df.drop(columns=['gender_male', 'multiple_lines_no_phone_service',
       'multiple_lines_yes', 'online_security_no_internet_service',
       'online_security_yes', 'online_backup_no_internet_service',
       'online_backup_yes', 'device_protection_no_internet_service',
       'device_protection_yes', 'tech_support_no_internet_service',
       'tech_support_yes', 'streaming_tv_no_internet_service',
       'streaming_tv_yes', 'streaming_movies_no_internet_service',
       'streaming_movies_yes', 'contract_type_one_year',
       'contract_type_two_year', 'internet_service_type_fiber_optic',
       'internet_service_type_none', 'payment_type_credit_card_automatic',
       'payment_type_electronic_check', 'payment_type_mailed_check']).head(1).T,
        df.drop(columns=['gender_male', 'multiple_lines_no_phone_service',
       'multiple_lines_yes', 'online_security_no_internet_service',
       'online_security_yes', 'online_backup_no_internet_service',
       'online_backup_yes', 'device_protection_no_internet_service',
       'device_protection_yes', 'tech_support_no_internet_service',
       'tech_support_yes', 'streaming_tv_no_internet_service',
       'streaming_tv_yes', 'streaming_movies_no_internet_service',
       'streaming_movies_yes', 'contract_type_one_year',
       'contract_type_two_year', 'internet_service_type_fiber_optic',
       'internet_service_type_none', 'payment_type_credit_card_automatic',
       'payment_type_electronic_check', 'payment_type_mailed_check']).dtypes.T], axis=1)

                                  0        0
customer_id              0002-ORFBO   object
gender                       Female   object
senior_citizen                    0    int64
partner                           1    int64
dependents                        1    int64
tenure                            9    int64
phone_service                     1    int64
multiple_lines                   No   object
online_security                  No   object
online_backup                   Yes   object
device_protection                No   object
tech_support                    Yes   object
streaming_tv                    Yes   object
streaming_movies                 No   object
paperless_billing                 1    int64
monthly_charges                65.6  float64
total_charges                 593.3  float64
churn                             0    int64
contract_type              One year   object
internet_service_type           DSL   object
payment_type           Mailed check   object

In [21]:
for col in df.columns:
    print(df[col].value_counts())

0002-ORFBO    1
6616-AALSR    1
6625-UTXEW    1
6625-IUTTT    1
6625-FLENO    1
             ..
3352-RICWQ    1
3352-ALMCK    1
3351-NQLDI    1
3351-NGXYI    1
9995-HOTOH    1
Name: customer_id, Length: 7043, dtype: int64
Male      3555
Female    3488
Name: gender, dtype: int64
0    5901
1    1142
Name: senior_citizen, dtype: int64
0    3641
1    3402
Name: partner, dtype: int64
0    4933
1    2110
Name: dependents, dtype: int64
1     613
72    362
2     238
3     200
4     176
     ...
28     57
39     56
44     51
36     50
0      11
Name: tenure, Length: 73, dtype: int64
1    6361
0     682
Name: phone_service, dtype: int64
No                  3390
Yes                 2971
No phone service     682
Name: multiple_lines, dtype: int64
No                     3498
Yes                    2019
No internet service    1526
Name: online_security, dtype: int64
No                     3088
Yes                    2429
No internet service    1526
Name: online_backup, dtype: int64
No                     3095
Yes                    2422
No internet service    1526
Name: device_protection, dtype: int64
No                     3473
Yes                    2044
No internet service    1526
Name: tech_support, dtype: int64
No                     2810
Yes                    2707
No internet service    1526
Name: streaming_tv, dtype: int64
No                     2785
Yes                    2732
No internet service    1526
Name: streaming_movies, dtype: int64
1    4171
0    2872
Name: paperless_billing, dtype: int64
20.05     61
19.85     45
19.95     44
19.90     44
20.00     43
          ..
116.55     1
106.85     1
68.55      1
108.80     1
67.85      1
Name: monthly_charges, Length: 1585, dtype: int64
0.00       11
20.20      11
19.75       9
19.90       8
20.05       8
           ..
2387.75     1
6302.80     1
2058.50     1
829.55      1
3707.60     1
Name: total_charges, Length: 6531, dtype: int64
0    5174
1    1869
Name: churn, dtype: int64
Month-to-month    3875
Two year          1695
One year          1473
Name: contract_type, dtype: int64
Fiber optic    3096
DSL            2421
None           1526
Name: internet_service_type, dtype: int64
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: payment_type, dtype: int64
1    3555
0    3488
Name: gender_male, dtype: int64
0    6361
1     682
Name: multiple_lines_no_phone_service, dtype: int64
0    4072
1    2971
Name: multiple_lines_yes, dtype: int64
0    5517
1    1526
Name: online_security_no_internet_service, dtype: int64
0    5024
1    2019
Name: online_security_yes, dtype: int64
0    5517
1    1526
Name: online_backup_no_internet_service, dtype: int64
0    4614
1    2429
Name: online_backup_yes, dtype: int64
0    5517
1    1526
Name: device_protection_no_internet_service, dtype: int64
0    4621
1    2422
Name: device_protection_yes, dtype: int64
0    5517
1    1526
Name: tech_support_no_internet_service, dtype: int64
0    4999
1    2044
Name: tech_support_yes, dtype: int64
0    5517
1    1526
Name: streaming_tv_no_internet_service, dtype: int64
0    4336
1    2707
Name: streaming_tv_yes, dtype: int64
0    5517
1    1526
Name: streaming_movies_no_internet_service, dtype: int64
0    4311
1    2732
Name: streaming_movies_yes, dtype: int64
0    5570
1    1473
Name: contract_type_one_year, dtype: int64
0    5348
1    1695
Name: contract_type_two_year, dtype: int64
0    3947
1    3096
Name: internet_service_type_fiber_optic, dtype: int64
0    5517
1    1526
Name: internet_service_type_none, dtype: int64
0    5521
1    1522
Name: payment_type_credit_card_automatic, dtype: int64
0    4678
1    2365
Name: payment_type_electronic_check, dtype: int64
0    5431
1    1612
Name: payment_type_mailed_check, dtype: int64